#!/usr/bin/env bash

set -eoux pipefail
echo $DB_LOCAL_URL
psql -f scripts/setup_local_db.sql -v ON_ERROR_STOP=1 -v db_name=$DB_NAME -v db_user=$DB_USER -v db_password=$DB_PASSWORD -v db_url=$DB_LOCAL_URL -v db_schema=$DB_SCHEMA -e
./manage.py makemigrations
./manage.py migrate
psql -d $DB_NAME -c 'ALTER TABLE auth_user ADD CONSTRAINT uniq_email UNIQUE (email);'
